### ISSUE TITLE
Error using module 

### ISSUE THREAD

**Issue by schliack** [soef/ioBroker.wifilight#12]
Hello,
after installing the module i got this error in logfile : 

ost.raspberrypi | 2017-11-07 13:01:45.231 | info | Restart adapter system.adapter.wifilight.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2017-11-07 13:01:45.231 | error | instance system.adapter.wifilight.0 terminated with code 1 ()
Caught | 2017-11-07 13:01:45.230 | error | by controller[0]: at startup (bootstrap_node.js:149:9)
Caught | 2017-11-07 13:01:45.230 | error | by controller[0]: at run (bootstrap_node.js:383:7)
Caught | 2017-11-07 13:01:45.230 | error | by controller[0]: at Module.runMain (module.js:604:10)
Caught | 2017-11-07 13:01:45.229 | error | by controller[0]: at Function.Module._load (module.js:438:3)
Caught | 2017-11-07 13:01:45.229 | error | by controller[0]: at tryModuleLoad (module.js:446:12)
Caught | 2017-11-07 13:01:45.229 | error | by controller[0]: at Module.load (module.js:487:32)
Caught | 2017-11-07 13:01:45.228 | error | by controller[0]: at Object.Module._extensions..js (module.js:579:10)
Caught | 2017-11-07 13:01:45.228 | error | by controller[0]: at Module._compile (module.js:570:32)
Caught | 2017-11-07 13:01:45.228 | error | by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.wifilight/wifilight.js:20:20)
Caught | 2017-11-07 13:01:45.227 | error | by controller[0]: at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1141:23)
Caught | 2017-11-07 13:01:45.227 | error | by controller[0]: TypeError: fns.adapter is not a function
Caught | 2017-11-07 13:01:45.227 | error | by controller[0]: ^
Caught | 2017-11-07 13:01:45.226 | error | by controller[0]: fns.adapter = fns.adapter(options);
Caught | 2017-11-07 13:01:45.225 | error | by controller[0]: /opt/iobroker/node_modules/soef/soef.js:1141
host.raspberrypi | 2017-11-07 13:01:44.283 | info | instance system.adapter.wifilight.0 started with pid 4843

The networkdevices will not be found (LD382)

Cheers 
Andreas

**Comment by jogibear9988** [comment]
This issue was moved to iobroker-community-adapters/ioBroker.wifilight-community#2
