### ISSUE TITLE
Adapter startet nicht.

### ISSUE THREAD

**Issue by matze1708** [soef/ioBroker.wifilight#14]
Hallo,

der Adapter startet nicht und bringt Fehler ins log.
Forum Thread:
http://forum.iobroker.net/viewtopic.php?f=20&t=9270&p=99007#p99007

Fehler:

`node node_modules/iobroker.wifilight/wifilight.js --logs --force
/opt/iobroker/node_modules/soef/soef.js:1141
    fns.adapter = fns.adapter(options);
                      ^

TypeError: fns.adapter is not a function
    at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1141:23)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.wifilight/wifilight.js:20:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)`

LOG:

> 

host.ioBroker-RasPi | 2017-11-26 11:42:42.830 | error | instance system.adapter.wifilight.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2017-11-26 11:42:42.830 | error | by controller[0]: at startup (bootstrap_node.js:149:9)
Caught | 2017-11-26 11:42:42.830 | error | by controller[0]: at run (bootstrap_node.js:383:7)
Caught | 2017-11-26 11:42:42.829 | error | by controller[0]: at Module.runMain (module.js:604:10)
Caught | 2017-11-26 11:42:42.829 | error | by controller[0]: at Function.Module._load (module.js:438:3)
Caught | 2017-11-26 11:42:42.829 | error | by controller[0]: at tryModuleLoad (module.js:446:12)
Caught | 2017-11-26 11:42:42.829 | error | by controller[0]: at Module.load (module.js:487:32)
Caught | 2017-11-26 11:42:42.829 | error | by controller[0]: at Object.Module._extensions..js (module.js:579:10)
Caught | 2017-11-26 11:42:42.828 | error | by controller[0]: at Module._compile (module.js:570:32)
Caught | 2017-11-26 11:42:42.828 | error | by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.wifilight/wifilight.js:20:20)
Caught | 2017-11-26 11:42:42.828 | error | by controller[0]: at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1141:23)
Caught | 2017-11-26 11:42:42.828 | error | by controller[0]: TypeError: fns.adapter is not a function
Caught | 2017-11-26 11:42:42.827 | error | by controller[0]: ^
Caught | 2017-11-26 11:42:42.827 | error | by controller[0]: fns.adapter = fns.adapter(options);
Caught | 2017-11-26 11:42:42.824 | error | by controller[0]: /opt/iobroker/node_modules/soef/soef.js:1141

**Comment by soef** [comment]
Hallo, da muss bei dir noch eine altes soef Modul im Einsatz sein. Mache einmal ein Update des Wifilight Adapters, oder deinstalliere und installiere ihn neu. Oder du führst 
npm install soef 
im node_modules/iobroker.wifilight Verzeichnis.

**Comment by matze1708** [comment]
Tatsächlich.... "sudo npm install soef" hat es gelöst.... zumindest ist er direkt mal grün.

Spricht der auch dieses magicHome?

https://www.amazon.de/Kontrolleur-Fernbedienung-Steuerung-Controller-RGBW/dp/B075KHJ871/ref=sr_1_1?ie=UTF8&qid=1513776608&sr=8-1&keywords=led+rgbw+controller




Vielen Dank für deine Hilfe.

**Comment by soef** [comment]
Die Lichterkette wird ja nicht per WLAN sondern per Infrarot gesteuert.  Funktioniert also mit diesem Adapter nicht. Du kannst aber den Broadlink oder Logitech Hub Adapter mit der entsprechenden Hardware verwenden und die Tasten der Fernbedienung anlernen.

**Comment by matze1708** [comment]
Ich kann doch die lichtstreifen per wlan auch am iPhone steuern.

**Comment by soef** [comment]
Ups, hatte nur die IR Fernbedienung gesehen. Aber dann kann ich nicht sagen ob der Kontroller auch gesteuert werden kann.

**Comment by matze1708** [comment]
Er findet ihn unter ak001-zj200

**Comment by soef** [comment]
Dann müsste es ja mit dem gemergeten Pull Request funktionieren, oder?

**Comment by matze1708** [comment]
Leider nein.
Also starten tut er. Nur das device nicht einbinden

**Comment by soef** [comment]
Ich habe nun noch ein paar Änderungen vorgenommen. Eigentlich ist die Geräte-Bezeichnung nur beim Ermitteln neuer Geräte notwendig. Wenn IP, Port und Geräte Typ richtig konfiguriert sind ist die Bezeichnung irrelevant.

**Comment by matze1708** [comment]
Jetzt bekomme ich diese Meldung 


wifilight.0	2017-12-26 21:15:27.316	error	wrong device type. not yet supported!
wifilight.0	2017-12-26 21:15:27.314	error	Known types are: LW12, LD382A, LD382, UFO, MiLight, MiLightRGB, MiLightW
wifilight.0	2017-12-26 21:15:27.314	error	config.device.type (AK001-ZJ200) is not a known device type. Skipping this device!

**Comment by soef** [comment]
Der Geräte Type scheint leer zu sein. Es müsste LD382A sein. Schaue mal in die Spalte Type in der Konfiguration.

**Comment by matze1708** [comment]
Jetzt klappt es! 
Er hatte im auto discover den typ nicht gesetzt.

Daher ging es wahrscheinlich nicht.

**Comment by soef** [comment]
Eigentlich sollte der Typ erkannt werden. Kannst Du noch einmal die Instance deinstallieren und wieder neu installieren? Oder für einen Test eine zweite Instanz installieren und ein auto discover durchführen?

**Comment by jogibear9988** [comment]
This issue was moved to iobroker-community-adapters/ioBroker.wifilight-community#3

**Comment by Rumpelstilzche** [comment]
moin moin, gibt es hierfür schon eine lösung? bei mir geht auch nichts
