### ISSUE TITLE
Adapter startet nicht sobald ein Typ eingetragen ist

### ISSUE THREAD

**Issue by nimit1001** [soef/iobroker.wifilight#21]
Ich hoffe ich bekomme hier noch einige Tipps: Mein Problem ist das der Adapter ohne ein Gerät problemlos läuft (grüner Status). Sobald ich ein Gerät suche findet er den "AK001-ZJ200" sowie eine IP, den Typ (LD382A) den Port 5577 sowie Pollintervall (30)

Im Anschluss ist der Adapter rot. Log kommt gleich noch. Nach einigem herumprobieren (Mehrfaches neuinstallieren des Adapter, Update der Komponente und manuelle Überprüfung der Datei (Soef-Version etc.)) habe ich dann herausgefunden das der Adapter läuft sobald ich den Typ des WIFI-Controllers entferne. Allerdings bekomme ich dann natürlich die Fehlermeldung dass der Typ unbekannt ist. (Logisch wenn kein Typ eingetragen ist)

Hier noch der Log wenn ein Controller eingetragen ist. Inklusive Typ:

host.raspberrypi | 2018-07-15 02:34:23.534 | info | Restart adapter system.adapter.wifilight.0 because enabled
-- | -- | -- | --
host.raspberrypi | 2018-07-15 02:34:23.534 | error | instance system.adapter.wifilight.0 terminated with code 0 (OK)
Caught | 2018-07-15 02:34:23.534 | error | by controller[0]: at Socket.onack (/root/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
Caught | 2018-07-15 02:34:23.534 | error | by controller[0]: at Socket.<anonymous> (/root/node_modules/iobroker.js-controller/lib/adapter.js:2281:25)
Caught | 2018-07-15 02:34:23.534 | error | by controller[0]: at /root/node_modules/iobroker.wifilight/node_modules/soef/soef.js:848:21
Caught | 2018-07-15 02:34:23.534 | error | by controller[0]: at safeCallback (/root/node_modules/iobroker.wifilight/node_modules/soef/soef.js:188:13)
Caught | 2018-07-15 02:34:23.534 | error | by controller[0]: at /root/node_modules/iobroker.wifilight/node_modules/soef/soef.js:1297:9
Caught | 2018-07-15 02:34:23.533 | error | by controller[0]: at main (/root/node_modules/iobroker.wifilight/wifilight.js:917:54)
Caught | 2018-07-15 02:34:23.533 | error | by controller[0]: at WifiLight.run (/root/node_modules/iobroker.wifilight/wifilight.js:170:10)
Caught | 2018-07-15 02:34:23.533 | error | by controller[0]: at WifiLight.createDevice (/root/node_modules/iobroker.wifilight/wifilight.js:197:19)
Caught | 2018-07-15 02:34:23.533 | error | by controller[0]: at CDevice.getFullId (/root/node_modules/iobroker.wifilight/node_modules/soef/soef.js:1113:20)
Caught | 2018-07-15 02:34:23.533 | error | by controller[0]: at dcs (/root/node_modules/iobroker.wifilight/node_modules/soef/soef.js:304:33)
Caught | 2018-07-15 02:34:23.532 | error | by controller[0]: TypeError: Cannot read property '0' of undefined
wifilight.0 | 2018-07-15 02:34:23.503 | error | at Socket.onack (/root/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
wifilight.0 | 2018-07-15 02:34:23.503 | error | at Socket.<anonymous> (/root/node_modules/iobroker.js-controller/lib/adapter.js:2281:25)
wifilight.0 | 2018-07-15 02:34:23.503 | error | at /root/node_modules/iobroker.wifilight/node_modules/soef/soef.js:848:21
wifilight.0 | 2018-07-15 02:34:23.503 | error | at safeCallback (/root/node_modules/iobroker.wifilight/node_modules/soef/soef.js:188:13)
wifilight.0 | 2018-07-15 02:34:23.503 | error | at /root/node_modules/iobroker.wifilight/node_modules/soef/soef.js:1297:9
wifilight.0 | 2018-07-15 02:34:23.503 | error | at main (/root/node_modules/iobroker.wifilight/wifilight.js:917:54)
wifilight.0 | 2018-07-15 02:34:23.503 | error | at WifiLight.run (/root/node_modules/iobroker.wifilight/wifilight.js:170:10)
wifilight.0 | 2018-07-15 02:34:23.503 | error | at WifiLight.createDevice (/root/node_modules/iobroker.wifilight/wifilight.js:197:19)
wifilight.0 | 2018-07-15 02:34:23.503 | error | at CDevice.getFullId (/root/node_modules/iobroker.wifilight/node_modules/soef/soef.js:1113:20)
wifilight.0 | 2018-07-15 02:34:23.503 | error | at dcs (/root/node_modules/iobroker.wifilight/node_modules/soef/soef.js:304:33)
wifilight.0 | 2018-07-15 02:34:23.503 | error | TypeError: Cannot read property '0' of undefined
wifilight.0 | 2018-07-15 02:34:23.502 | error | uncaught exception: Cannot read property '0' of undefined
wifilight.0 | 2018-07-15 02:34:23.427 | info | starting. Version 0.2.1 in /root/node_modules/iobroker.wifilight, node: v8.11.3

Ich hoffe das jemand eine Idee hat woran das liegen kann und bedanke mich im Voraus schonmal.

**Comment by ghost** [comment]
Ich hatte dasselbe Problem beim Magic Home WiFi Controller, "v4" mit Adapter-Version 0.2.1.

Nach langem herumprobieren habe ich die Adapter-Version 0.2.0 installiert, damit klappt es dann bei mir ohne den obigen Fehler. Siehe auch im Forum: https://forum.iobroker.net/viewtopic.php?f=20&t=16868

**Comment by jogibear9988** [comment]
This issue was moved to iobroker-community-adapters/ioBroker.wifilight-community#6
