### ISSUE TITLE
Sometimes dev is null

### ISSUE THREAD

**Issue by GermanBluefox** [soef/ioBroker.wifilight#7]
Sometimes dev is null

https://github.com/soef/ioBroker.wifilight/blob/master/wifilight.js#L908

```
host.ioBroker-Pi	2017-05-13 21:55:36.232	error	instance system.adapter.wifilight.0 terminated with code 0 (OK)
wifilight.0	2017-05-13 21:55:36.208	error	TypeError: Cannot read property 'pollIntervall' of undefined at /opt/iobroker/node_modules/iobroker.wifilight/wifilight.js:910:39 at Array.forEach (native) at normalizeConfig (/opt/iobroke
wifilight.0	2017-05-13 21:55:36.207	error	uncaught exception: Cannot read property 'pollIntervall' of undefined
hm-rpc.1	2017-05-13 21:55:36.149	info	Disconnected
wifilight.0	2017-05-13 21:55:36.106	info	starting. Version 0.1.4 in /opt/iobroker/node_modules/iobroker.wifilight, node: v4.8.3
host.ioBroker-Pi	2017-05-13 21:55:04.436	info	Restart adapter system.adapter.wifilight.0 because enabled
host.ioBroker-Pi	2017-05-13 21:55:04.435	error	instance system.adapter.wifilight.0 terminated with code 0 (OK)
wifilight.0	2017-05-13 21:55:04.417	info	terminating
wifilight.0	2017-05-13 21:55:04.408	error	at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:236:12)
wifilight.0	2017-05-13 21:55:04.408	error	at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:312:9)
wifilight.0	2017-05-13 21:55:04.408	error	at Socket. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2213:25)
wifilight.0	2017-05-13 21:55:04.408	error	at /opt/iobroker/node_modules/iobroker.wifilight/node_modules/soef/soef.js:711:21
wifilight.0	2017-05-13 21:55:04.408	error	at safeCallback (/opt/iobroker/node_modules/iobroker.wifilight/node_modules/soef/soef.js:162:13)
wifilight.0	2017-05-13 21:55:04.408	error	at /opt/iobroker/node_modules/iobroker.wifilight/node_modules/soef/soef.js:1064:9
wifilight.0	2017-05-13 21:55:04.408	error	at main (/opt/iobroker/node_modules/iobroker.wifilight/wifilight.js:935:5)
wifilight.0	2017-05-13 21:55:04.408	error	at normalizeConfig (/opt/iobroker/node_modules/iobroker.wifilight/wifilight.js:906:20)
wifilight.0	2017-05-13 21:55:04.408	error	at Array.forEach (native)
wifilight.0	2017-05-13 21:55:04.408	error	at /opt/iobroker/node_modules/iobroker.wifilight/wifilight.js:910:39
wifilight.0	2017-05-13 21:55:04.408	error	TypeError: Cannot read property 'pollIntervall' of undefined
wifilight.0	2017-05-13 21:55:04.396	error	uncaught exception: Cannot read property 'pollIntervall' of undefined
```
http://forum.iobroker.net/viewtopic.php?f=17&t=6497

**Comment by soef** [comment]
Hi, I think it depends on a unknown device name.  In a new vesion 0.1.15 this will be checked and the reason can be found in the error log.

I hope this will help you.
